# Config

site_name: Abyss Docs
site_description: Abyss Engine Documentation
site_author: Aaron Harwin
repo_name: AbyssEngine
repo_url: https://github.com/xexaaron/AbyssEngine

# Navigation

nav:
  - Home: "index.md"
  - Object: "pages/Object.md"
  - Resource:
      - Overview: "pages/Resource.md"
      - Shaders: "pages/Shaders.md"
  - Text: "pages/Text.md" 

# Theme

theme: 
  name: material
  font: 
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Dark mode
    primary: blue
    accent: deep purple
  features:
    - content.code.copy

# Extensions

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.keys  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  